spring.application.name=evente-set

# ==========================================
# Configurações do Banco de Dados (MySQL)
# ==========================================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/eventeset_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# Configurações do JPA / Hibernate
# ==========================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never

# ==========================================
# Configurações do Docker e Segurança
# ==========================================

spring.docker.compose.enabled=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Configurao de porta para Render
server.port=${PORT:8080}
