spring.application.name=evente-set

# ==========================================
# Configurações do Banco de Dados (MySQL)
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3307/eventeset_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# Configurações do JPA / Hibernate
# ==========================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never

# ==========================================
# Configurações do Docker e Segurança
# ==========================================
# Como você já subiu o docker manualmente pelo terminal, vamos desativar
# a tentativa do Spring Boot de procurá-lo e iniciá-lo, o que estava causando o crash na sua IDE.
spring.docker.compose.enabled=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
